version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: flowrunner-postgres
    environment:
      POSTGRES_USER: flowrunner
      POSTGRES_PASSWORD: flowrunner
      POSTGRES_DB: flowrunner_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowrunner -d flowrunner_db"]
      interval: 2s
      timeout: 5s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: flowrunner-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 15
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
